# create environment : conda env create -f environment.yml
# update dependencies: conda env update -f environment.yml
# remove environment : conda env remove -n RAiDER
# enter  environment : conda activate RAiDER
# exit   environment : conda deactivate
name: RAiDER
channels:
 - conda-forge
 - nodefaults
dependencies:
 - python>=3.8
 - pip
 # For running
 - cdsapi
 - cfgrib
 - cmake
 - cxx-compiler
 - cython
 - dask
 - dem_stitcher>=2.3.1
 - ecmwf-api-client
 - h5py
 - herbie-data
 - h5netcdf
 - isce3>=0.9.0
 - lxml
 - matplotlib
 - netcdf4
 - numpy
 - pandas
 - progressbar
 - pydap>3.2.2
 - pyproj>=2.2.0
 - pyyaml
 - rasterio>=1.3.0
 - requests
 - s3fs
 - scipy
 - shapely
 - sysroot_linux-64
 - tqdm
 - xarray
 # For packaging and testing
 - autopep8
 - pytest
 - pytest-cov
 - pytest-timeout
 - pytest-console-scripts
 - setuptools_scm >=6.2
 - sentineleof

 # For RAiDER-docs
 - jupyterlab
 - jupyter_contrib_nbextensions
 - wand
